CREATE DATABASE IF NOT EXISTS recetas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE recetas;


CREATE TABLE IF NOT EXISTS recipes (
id INT AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(512) NOT NULL,
shortcode VARCHAR(64) NOT NULL,
author VARCHAR(255) NULL,
caption MEDIUMTEXT NULL,
image_url VARCHAR(1024) NULL,
posted_at DATETIME NULL,
likes INT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY uq_shortcode (shortcode),
INDEX idx_created_at (created_at)
) ENGINE=InnoDB;